### ISSUE TITLE
tugboat doesn't work with team accounts, because they use api v2

### ISSUE THREAD

**Issue by oryband** [pearkes/tugboat#168]
```bash
$ DEBUG=1 tugboat droplets
I, [2015-06-02T12:12:38.275351 #8815]  INFO -- : Started GET request to: https://api.digitalocean.com/droplets?client_id=XXX&api_key=XXX
D, [2015-06-02T12:12:38.275687 #8815] DEBUG -- : Request Headers:
----------------
User-Agent : Faraday v0.8.9

Request Body:
-------------


I, [2015-06-02T12:12:39.069769 #8815]  INFO -- : Response from https://api.digitalocean.com/droplets?client_id=XXX&api_key=XXX; Status: 200; Time: 794.3ms
D, [2015-06-02T12:12:39.070229 #8815] DEBUG -- : Response Headers:
----------------
server                 : cloudflare-nginx
date                   : Tue, 02 Jun 2015 09:12:39 GMT
content-type           : application/json; charset=utf-8
transfer-encoding      : chunked
connection             : close
set-cookie             : __cfduid=XXX; expires=Wed, 01-Jun-16 09:12:38 GMT; path=/; domain=.digitalocean.com; HttpOnly
status                 : 200 OK
x-frame-options        : SAMEORIGIN
x-xss-protection       : 1; mode=block
x-content-type-options : nosniff
cache-control          : max-age=0, private, must-revalidate
x-request-id           : XXX
x-runtime              : 0.141621
cf-ray                 : XXX-LHR

Response Body:
-------------
#<Hashie::Rash droplets=[] status="OK">

You don't appear to have any droplets.
Try creating one with `tugboat create`
```
I've just created a team account, but I'm not sure it's related. This happened before and after i re-executed `tugboat authorize` and filled all the necessary details. Any idea what's wrong?

Note I deleted anything that resembled a key/hash for security purposes :)

**Comment by oryband** [comment]
@fuzzyami

**Comment by oryband** [comment]
UPDATE: this is a bug in digitalocean's api.

**Comment by oryband** [comment]
UPDATE: API v1 doesn't work with team accounts. The solution to this is to update this repo to use v2 :\
#122 #161 

any progress on this?

**Comment by petems** [comment]
Haven't had a lot of spare time to work on the API 2.0 support, I might just do an alpha for people to start testing things

https://github.com/pearkes/tugboat/issues/161

**Comment by petems** [comment]
@oryband Can you try using the latest `v2.0.0.ALPHA` release and tell me if that works for you?

**Comment by alekseyp** [comment]
On OS X getting next error:

```
bash-3.2$ sudo gem install tugboat:2.0.0.ALPHA
Fetching: faraday-0.9.1.gem (100%)
Successfully installed faraday-0.9.1
Fetching: hashie-3.4.2.gem (100%)
Successfully installed hashie-3.4.2
Fetching: barge-0.10.0.gem (100%)
Successfully installed barge-0.10.0
Fetching: tugboat-2.0.0.ALPHA.gem (100%)
***************************************
Successfully installed tugboat-2.0.0.ALPHA
Parsing documentation for faraday-0.9.1
Installing ri documentation for faraday-0.9.1
Parsing documentation for hashie-3.4.2
Installing ri documentation for hashie-3.4.2
Parsing documentation for barge-0.10.0
Installing ri documentation for barge-0.10.0
Parsing documentation for tugboat-2.0.0.ALPHA
Installing ri documentation for tugboat-2.0.0.ALPHA
4 gems installed
```
```
bash-3.2$ tugboat version
Tugboat 2.0.0.ALPHA
```
```
bash-3.2$ tugboat authorize
Note: You can get this information from https://cloud.digitalocean.com/api_access
Also Note: Tugboat is setup to work with v1 of the Digital Ocean API (https://developers.digitalocean.com/v1/)

Enter your client key: 
Enter your API key: _MY_V2_KEY
Enter your SSH key path (optional, defaults to ~/.ssh/id_rsa): 
Enter your SSH user (optional, defaults to root): 
Enter your SSH port number (optional, defaults to 22): 

To retrieve region, image, size and key ID's, you can use the corresponding tugboat command, such as `tugboat images`.
Defaults can be changed at any time in your ~/.tugboat configuration file.

Enter your default region ID (optional, defaults to 8 (New York 3)): 
Enter your default image ID (optional, defaults to 9801950 (Ubuntu 14.04 x64)): 
Enter your default size ID (optional, defaults to 66 (512MB)): 
Enter your default ssh key ID (optional, defaults to none): 
Enter your default for private networking (optional, defaults to false): 
Enter your default for enabling backups (optional, defaults to false): 
/Library/Ruby/Gems/2.0.0/gems/tugboat-2.0.0.ALPHA/lib/tugboat/config.rb:95:in `create_config_file': wrong number of arguments (11 for 10) (ArgumentError)
	from /Library/Ruby/Gems/2.0.0/gems/tugboat-2.0.0.ALPHA/lib/tugboat/middleware/ask_for_credentials.rb:26:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/tugboat-2.0.0.ALPHA/lib/tugboat/middleware/inject_configuration.rb:10:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/middleware-0.1.0/lib/middleware/runner.rb:31:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/middleware-0.1.0/lib/middleware/builder.rb:102:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/tugboat-2.0.0.ALPHA/lib/tugboat/cli.rb:38:in `authorize'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/tugboat-2.0.0.ALPHA/bin/tugboat:10:in `<top (required)>'
	from /usr/bin/tugboat:23:in `load'
	from /usr/bin/tugboat:23:in `<main>'
```
```
bash-3.2$ ruby -v
ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
```
I'm leaving client id empty, also, tried to put simple 'na' but got exactly the same problem.

**Comment by petems** [comment]
Yeah, I haven't got the auto-auth working with the 2.0 API yet, you'll have to manually add it to the `~/.tugboat` file:

```
---
authentication:
  access_token: foo
```

**Comment by oryband** [comment]
@petems sorry, my team reverted to v1 so i can't test that now

**Comment by alekseyp** [comment]
@petems , it's working, i can see list of droplets, but some commands don't work, like `tugboat create`. 

```
➜  ~ tugboat verify
Authentication with DigitalOcean was successful.
```

```
➜  ~ tugboat create testing11
Queueing creation of droplet 'testing11'.../Library/Ruby/Gems/2.0.0/gems/tugboat-2.0.0.ALPHA/lib/tugboat/middleware/create_droplet.rb:34:in `call': undefined method `droplets' for #<Barge::Client:0x007faf64b6f038> (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/tugboat-2.0.0.ALPHA/lib/tugboat/middleware/inject_client.rb:14:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/tugboat-2.0.0.ALPHA/lib/tugboat/middleware/check_configuration.rb:19:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/tugboat-2.0.0.ALPHA/lib/tugboat/middleware/inject_configuration.rb:10:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/middleware-0.1.0/lib/middleware/runner.rb:31:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/middleware-0.1.0/lib/middleware/builder.rb:102:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/tugboat-2.0.0.ALPHA/lib/tugboat/cli.rb:164:in `create'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/tugboat-2.0.0.ALPHA/bin/tugboat:10:in `<top (required)>'
	from /usr/bin/tugboat:23:in `load'
	from /usr/bin/tugboat:23:in `<main>'
```

Maybe it's my  _~/.tugboat_ file. Here it's content

```
---
authentication:
  access_token: _KEY_
ssh:
  ssh_user: root
  ssh_key_path: ~/.ssh/id_rsa
  ssh_port: 22
defaults:
  region: 8
  image: 9801950
  size: 66
  ssh_key: _ID_
  private_networking: false
  backups_enabled: false
```

**Comment by petems** [comment]
Nah, the create function wasn't working at the time, let me release the second iteration of the Alpha

**Comment by alekseyp** [comment]
I can ssh in now. But creating still doesn't work. Do you want me to go over all commands and provide list  that failed and all errors?

**Comment by petems** [comment]
@alekseyp That would be great if you could!

For creating servers, can you try changing the ~/.tugboat settings for servers to the following:

```
defaults:
  region: nyc2
  image: ubuntu-14-04-x64
  size: 512mb
  ssh_key: ''
  private_networking: 'false'
  backups_enabled: 'false'
```

The new API uses different strings for creating servers.

**Comment by alekseyp** [comment]
Alright, here we go. I hope it's readable.

```
Commands:
  tugboat add-key KEY-NAME                             # WORKS
  tugboat authorize                                    # DOES NOT WORK
  tugboat config                                       # WORKS
  tugboat create NAME                                  # WORKS
  tugboat destroy FUZZY_NAME                           # WORKS
  tugboat destroy_image FUZZY_NAME                     # DOES NOT WORK
  tugboat droplets                                     # WORKS
  tugboat halt FUZZY_NAME                              # WORKS
  tugboat help [COMMAND]                               # WORKS
  tugboat images [OPTIONS]                             # WORKS
  tugboat info FUZZY_NAME [OPTIONS]                    # DOES NOT WORK
  tugboat info_image FUZZY_NAME [OPTIONS]              # DOES NOT WORK
  tugboat keys                                         # WORKS
  tugboat password-reset FUZZY_NAME                    # WORKS
  tugboat rebuild FUZZY_NAME IMAGE_NAME                # DOES NOT WORK
  tugboat regions                                      # WORKS
  tugboat resize FUZZY_NAME -s, --size=N               # DOES NOT WORK
  tugboat restart FUZZY_NAME                           # WORKS
  tugboat sizes                                        # WORKS
  tugboat snapshot SNAPSHOT_NAME FUZZY_NAME [OPTIONS]  # DOES NOT WORK
  tugboat ssh FUZZY_NAME                               # WORKS
  tugboat start FUZZY_NAME                             # WORKS
  tugboat verify                                       # WORKS
  tugboat version                                      # WORKS
  tugboat wait FUZZY_NAME                              # WORKS
```



```
➜  ~ tugboat authorize
Note: You can get your Access Token from https://cloud.digitalocean.com/settings/tokens/new

/Library/Ruby/Gems/2.0.0/gems/tugboat-2.1.0.ALPHA/lib/tugboat/middleware/ask_for_credentials.rb:8:in `call': undefined local variable or method `access_token' for #<Tugboat::Middleware::AskForCredentials:0x007fcf590d1c38> (NameError)
	from /Library/Ruby/Gems/2.0.0/gems/tugboat-2.1.0.ALPHA/lib/tugboat/middleware/inject_configuration.rb:10:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/middleware-0.1.0/lib/middleware/runner.rb:31:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/middleware-0.1.0/lib/middleware/builder.rb:102:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/tugboat-2.1.0.ALPHA/lib/tugboat/cli.rb:38:in `authorize'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/tugboat-2.1.0.ALPHA/bin/tugboat:10:in `<top (required)>'
	from /usr/bin/tugboat:23:in `load'
	from /usr/bin/tugboat:23:in `<main>'
```
```
➜  ~ tugboat info test
Droplet fuzzy name provided. Finding droplet ID...done, 1234567 (test01)
done
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- pry (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/tugboat-2.1.0.ALPHA/lib/tugboat/middleware/info_droplet.rb:24:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/tugboat-2.1.0.ALPHA/lib/tugboat/middleware/find_droplet.rb:123:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/tugboat-2.1.0.ALPHA/lib/tugboat/middleware/inject_client.rb:14:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/tugboat-2.1.0.ALPHA/lib/tugboat/middleware/check_configuration.rb:19:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/tugboat-2.1.0.ALPHA/lib/tugboat/middleware/inject_configuration.rb:10:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/middleware-0.1.0/lib/middleware/runner.rb:31:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/middleware-0.1.0/lib/middleware/builder.rb:102:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/tugboat-2.1.0.ALPHA/lib/tugboat/cli.rb:312:in `info'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/tugboat-2.1.0.ALPHA/bin/tugboat:10:in `<top (required)>'
	from /usr/bin/tugboat:23:in `load'
	from /usr/bin/tugboat:23:in `<main>'
```
```
➜  ~ tugboat destroy_image testimage
Image fuzzy name provided. Finding image ID.../Library/Ruby/Gems/2.0.0/gems/tugboat-2.1.0.ALPHA/lib/tugboat/middleware/find_image.rb:71:in `call': undefined method `images' for #<Barge::Client:0x007fbdc2a9e7f0> (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/tugboat-2.1.0.ALPHA/lib/tugboat/middleware/inject_client.rb:14:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/tugboat-2.1.0.ALPHA/lib/tugboat/middleware/check_configuration.rb:19:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/tugboat-2.1.0.ALPHA/lib/tugboat/middleware/inject_configuration.rb:10:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/middleware-0.1.0/lib/middleware/runner.rb:31:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/middleware-0.1.0/lib/middleware/builder.rb:102:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/tugboat-2.1.0.ALPHA/lib/tugboat/cli.rb:247:in `destroy_image'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/tugboat-2.1.0.ALPHA/bin/tugboat:10:in `<top (required)>'
	from /usr/bin/tugboat:23:in `load'
	from /usr/bin/tugboat:23:in `<main>'
```
```
➜  ~ tugboat info_image testimage
Image fuzzy name provided. Finding image ID.../Library/Ruby/Gems/2.0.0/gems/tugboat-2.1.0.ALPHA/lib/tugboat/middleware/find_image.rb:71:in `call': undefined method `images' for #<Barge::Client:0x007fa73b9e84c0> (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/tugboat-2.1.0.ALPHA/lib/tugboat/middleware/inject_client.rb:14:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/tugboat-2.1.0.ALPHA/lib/tugboat/middleware/check_configuration.rb:19:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/tugboat-2.1.0.ALPHA/lib/tugboat/middleware/inject_configuration.rb:10:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/middleware-0.1.0/lib/middleware/runner.rb:31:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/middleware-0.1.0/lib/middleware/builder.rb:102:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/tugboat-2.1.0.ALPHA/lib/tugboat/cli.rb:330:in `info_image'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/tugboat-2.1.0.ALPHA/bin/tugboat:10:in `<top (required)>'
	from /usr/bin/tugboat:23:in `load'
	from /usr/bin/tugboat:23:in `<main>'
```

```
➜  ~ tugboat rebuild testing11 12790328
Droplet fuzzy name provided. Finding droplet ID...done, 1233455 (testing11)
Image fuzzy name provided. Finding image ID.../Library/Ruby/Gems/2.0.0/gems/tugboat-2.1.0.ALPHA/lib/tugboat/middleware/find_image.rb:71:in `call': undefined method `images' for #<Barge::Client:0x007fbfb2816928> (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/tugboat-2.1.0.ALPHA/lib/tugboat/middleware/find_droplet.rb:123:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/tugboat-2.1.0.ALPHA/lib/tugboat/middleware/inject_client.rb:14:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/tugboat-2.1.0.ALPHA/lib/tugboat/middleware/check_configuration.rb:19:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/tugboat-2.1.0.ALPHA/lib/tugboat/middleware/inject_configuration.rb:10:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/middleware-0.1.0/lib/middleware/runner.rb:31:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/middleware-0.1.0/lib/middleware/builder.rb:102:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/tugboat-2.1.0.ALPHA/lib/tugboat/cli.rb:198:in `rebuild'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/tugboat-2.1.0.ALPHA/bin/tugboat:10:in `<top (required)>'
	from /usr/bin/tugboat:23:in `load'
	from /usr/bin/tugboat:23:in `<main>'




➜  ~ tugboat rebuild testing11 '14.04 x64'
Droplet fuzzy name provided. Finding droplet ID...done, 1233455 (testing11)
Image fuzzy name provided. Finding image ID.../Library/Ruby/Gems/2.0.0/gems/tugboat-2.1.0.ALPHA/lib/tugboat/middleware/find_image.rb:71:in `call': undefined method `images' for #<Barge::Client:0x007ff3e2002980> (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/tugboat-2.1.0.ALPHA/lib/tugboat/middleware/find_droplet.rb:123:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/tugboat-2.1.0.ALPHA/lib/tugboat/middleware/inject_client.rb:14:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/tugboat-2.1.0.ALPHA/lib/tugboat/middleware/check_configuration.rb:19:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/tugboat-2.1.0.ALPHA/lib/tugboat/middleware/inject_configuration.rb:10:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/middleware-0.1.0/lib/middleware/runner.rb:31:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/middleware-0.1.0/lib/middleware/builder.rb:102:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/tugboat-2.1.0.ALPHA/lib/tugboat/cli.rb:198:in `rebuild'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/tugboat-2.1.0.ALPHA/bin/tugboat:10:in `<top (required)>'
	from /usr/bin/tugboat:23:in `load'
	from /usr/bin/tugboat:23:in `<main>'
```

```
➜  ~ tugboat snapshot testing11111 testing
Droplet fuzzy name provided. Finding droplet ID...done, 1233455 (testing11)
Warning: Droplet must be in a powered off state for snapshot to be successful
Queuing snapshot 'testing11111' for 6253568 (testing11).../Library/Ruby/Gems/2.0.0/gems/tugboat-2.1.0.ALPHA/lib/tugboat/middleware/snapshot_droplet.rb:13:in `call': undefined method `droplets' for #<Barge::Client:0x007fb079258e48> (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/tugboat-2.1.0.ALPHA/lib/tugboat/middleware/check_droplet_inactive.rb:12:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/tugboat-2.1.0.ALPHA/lib/tugboat/middleware/find_droplet.rb:123:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/tugboat-2.1.0.ALPHA/lib/tugboat/middleware/inject_client.rb:14:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/tugboat-2.1.0.ALPHA/lib/tugboat/middleware/check_configuration.rb:19:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/tugboat-2.1.0.ALPHA/lib/tugboat/middleware/inject_configuration.rb:10:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/middleware-0.1.0/lib/middleware/runner.rb:31:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/middleware-0.1.0/lib/middleware/builder.rb:102:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/tugboat-2.1.0.ALPHA/lib/tugboat/cli.rb:348:in `snapshot'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/tugboat-2.1.0.ALPHA/bin/tugboat:10:in `<top (required)>'
	from /usr/bin/tugboat:23:in `load'
	from /usr/bin/tugboat:23:in `<main>'
```
```
➜  ~ tugboat resize testing --size=1024
Droplet fuzzy name provided. Finding droplet ID...done, 1233455 (testing11)
Queuing resize for 6253568 (testing11).../Library/Ruby/Gems/2.0.0/gems/tugboat-2.1.0.ALPHA/lib/tugboat/middleware/resize_droplet.rb:9:in `call': undefined method `droplets' for #<Barge::Client:0x007fe26411a230> (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/tugboat-2.1.0.ALPHA/lib/tugboat/middleware/find_droplet.rb:123:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/tugboat-2.1.0.ALPHA/lib/tugboat/middleware/inject_client.rb:14:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/tugboat-2.1.0.ALPHA/lib/tugboat/middleware/check_configuration.rb:19:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/tugboat-2.1.0.ALPHA/lib/tugboat/middleware/inject_configuration.rb:10:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/middleware-0.1.0/lib/middleware/runner.rb:31:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/middleware-0.1.0/lib/middleware/builder.rb:102:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/tugboat-2.1.0.ALPHA/lib/tugboat/cli.rb:435:in `resize'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/tugboat-2.1.0.ALPHA/bin/tugboat:10:in `<top (required)>'
	from /usr/bin/tugboat:23:in `load'
	from /usr/bin/tugboat:23:in `<main>'
```

**Comment by petems** [comment]
@alekseyp Ok, I think I've fixed it, can you try the 2.0.0.pre1 release?

**Comment by alekseyp** [comment]
@petems , thanks!
Right away I see that SSH can't connect to public IP, it's alway using private, even with config changes or _-e_ option

```
➜  ~ tugboat ssh -e server1111
Droplet fuzzy name provided. Finding droplet ID...done, 1234567 (server1111)
Executing SSH (server1111)...
ssh: connect to host 10.10.10.11 port 22: Operation timed out
➜  ~ tugboat ssh delivery311 -e
Droplet fuzzy name provided. Finding droplet ID...done, 1234567 (server1111)
Executing SSH (server1111)...
ssh: connect to host 10.10.10.11 port 22: Operation timed out
```

```
➜  ~ tugboat config
Current Config (Keys Redacted)
Path: /Users/alekseyp/.tugboat
---
authentication:
  access_token: _KEY_
ssh:
  ssh_user: root
  ssh_key_path: ~/.ssh/id_rsa
  ssh_port: 22
defaults:
  region: nyc2
  image: ubuntu-14-04-x64
  size: 512mb
  ssh_key: ''
  private_networking: 'false'
  backups_enabled: 'false'
  use_public_ip: 'true'
```

**Comment by alekseyp** [comment]
```  tugboat authorize                                    # DOES NOT WORK```

**Comment by alekseyp** [comment]
Is there anyway to configure it to use public ip for SSH?

**Comment by petems** [comment]
@alekseyp Sorry was on holiday, I'll push up my fix and release another alpha of the gem.

**Comment by alekseyp** [comment]
Thanks! Can't wait for it.

**Comment by alekseyp** [comment]
Is there any update on that?

**Comment by petems** [comment]
@alekseyp Hey! Wanna try now with v2.0.0.pre2?

**Comment by alekseyp** [comment]
@petems it's still using private IP :(

**Comment by alekseyp** [comment]
Also, info fails now.
```
bash-3.2$ DEBUG=1 tugboat info MyVM 
Droplet fuzzy name provided. Finding droplet ID...done, 123456 (web01.MyVM.com)
done
/Library/Ruby/Gems/2.0.0/gems/tugboat-2.0.0.pre2/lib/tugboat/middleware/info_droplet.rb:36:in `call': undefined method `ip_address' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/tugboat-2.0.0.pre2/lib/tugboat/middleware/find_droplet.rb:134:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/tugboat-2.0.0.pre2/lib/tugboat/middleware/inject_client.rb:14:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/tugboat-2.0.0.pre2/lib/tugboat/middleware/check_configuration.rb:19:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/tugboat-2.0.0.pre2/lib/tugboat/middleware/inject_configuration.rb:10:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/middleware-0.1.0/lib/middleware/runner.rb:31:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/middleware-0.1.0/lib/middleware/builder.rb:102:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/tugboat-2.0.0.pre2/lib/tugboat/cli.rb:319:in `info'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/tugboat-2.0.0.pre2/bin/tugboat:10:in `<top (required)>'
	from /usr/bin/tugboat:23:in `load'
	from /usr/bin/tugboat:23:in `<main>'
```

**Comment by petems** [comment]
@alekseyp Try now? :+1:

**Comment by alekseyp** [comment]
@petems :ok: :+1: hallelujah 

Thanks a lot! ill do more tests tonight

**Comment by petems** [comment]
Yeah, I'm going to have to speed this up a bit, API 1.0 is EOL soon! :sob:
